# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options



before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$UPCOMING_SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$UPCOMING_SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts

after_script:
  - killall ssh-agent
  - date

stages:
  - test
  - deploy

deploy_master:
  stage: deploy
  environment:
    name: live/$CI_COMMIT_REF_NAME
    url: https://karriere24.de
  only:
    - master
  script:
    - dep -vvv  deploy
  resource_group: production

deploy_staging:
  stage: deploy
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: http://staging.karriere24.com
  except:
    - master
  script:
    dep -vvv deploy --branch=$CI_COMMIT_REF_NAME staging
  resource_group: staging

test:
 stage: test
 script:
   - pgrep ssh-agent
   - echo "do some tests"
