# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'   
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$UPCOMING_SSH_PRIVATE_KEY")
   - mkdir -p ~/.ssh
   - echo "$UPCOMING_SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
   
after_script:
  - killall ssh-agent
  - date

stages:
  - test
  - deploy
   
deploy_master:
 stage: deploy
 only: 
   - 57-geocoder-wegen-caching-upgraden
 script:
   - dep -vvv  deploy

deploy_staging:
 stage: deploy
 except: 
   - master
 script:
   - ls -l
   - echo "where we are? what shall we do?"

test:
 stage: test
 script:
   - pgrep ssh-agent
   - echo "do some tests"
