<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author cbleek
 * @license  MIT
 */ ?>
<?php

$this->headTitle('Über Karriere24');
$this->headscript()->appendScript('$(".alert").alert();');
$this->headScript()->appendFile($this->basepath('Karriere24/wow.min.js'));

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$siteName = $options->getSiteName();
$operator = $options->getOperator();

?>
<script>
    new WOW().init();
</script>

<style>
    section {
        margin-top: 50px;
    }
    .scroll-down {
        text-align: center;
        width: 100%;
    }
    .scroll-down .btn {
        border: 2px solid #d9230f;;
        border-radius: 100%;
        font-size: 30px;
        height: 50px;
        letter-spacing: normal;
        line-height: 50px;
        padding: 0;
        transition: all 0.5s ease 0s;
        width: 50px;
    }
    .scroll-down .btn:hover {
        border-color: rgba(255,165,0, 0.5);
        color: rgba(255,165,0, 0.5);
        outline: 0 none;
    }
    #jb-carousel {
	height: 300px;
    }
    .homepage{
        font-size: 6em;
    }
</style>
<a name="about"></a>
<section class="wow fadeIn">
    <div class="row">
        <div class="container">
<h1>Über <?php echo $siteName ?></h1>

<a name="impressum"></a>
<section class="wow bounceInUp">

    <h2>Impressum</h2>

    <p>Karriere24.com ist ein Service der Karriere.com Unternehmens- und Personalberatung UG (haftungsbeschränkt)</p>

    Ansprechpartner ist:

    <address>
        <div>Geschäftsführerin: <?php echo $operator['name'] ?></div>
        <div><?php echo $operator['street'] ?></div>
        <div><?php echo $operator['postalCode'] ?> <?php echo $operator['city'] ?></div>
    </address>

    <address>
        <div>Email: <?php echo $operator['email'] ?></div>
        <div>Tel: <?php echo $operator['phone'] ?></div>
    </address>
    
    <div>
        Amtsgericht Frankfurt/Main HRB 114547
    </div>
</section>

<div class="scroll-down">
    <a class="btn" href="#about">
        <i class="fa fa-angle-down fa-fw"></i>
    </a>
</div>
<a name="datenschutz"></a>

<section class="wow bounceInUp">
    <h2>Datenschutzerklärung</h2>
    <p>
        Betreiber der Seite ist <?php echo $operator['companyFullName'] ?>. im folgenden <?php echo $operator['companyShortName'] ?> genannt.
    </p>
    <p>
        <?php echo $operator['companyShortName'] ?> will Ihnen eine sichere und geschützte Nutzung der Webseite gewährleisten
        und geht deshalb verantwortungsbewusst mit Ihren Daten um. Das betrifft sowohl die Erhebung als auch die Verarbeitung
        und die Nutzung. Wie wir Ihre personengebundenen Daten verwenden, die Sie hier eingeben, erfahren Sie in
        der folgenden Erklärung. Ihre Daten werden entsprechend der gesetzlichen Bestimmungen zum Datenschutz,
        insbesondere das Bundesdatenschutzgesetz (BDSG) und das Gesetz über den Datenschutz bei Telediensten
        (TDDSG) geschützt. <?php echo $operator['companyShortName'] ?> trägt keine Verantwortung für die Datenschutzrichtlinien
        oder Praktiken anderer Webseiten, auf die wir Links gesetzt haben. Diese Datenschutzerklärung gilt nur
        für die Informationen, die wir über diese Website erheben. Die nachfolgenden Informationen erklären Ihnen,
        welche Daten während Ihres Besuchs auf der Homepage erfasst und wie diese genutzt werden:
    </p>
    <ol>
        <li class="wow fadeInLeft">
            <h4>Erhebung und Verarbeitung der Daten</h4>
            Informationen, die Ihr Browser uns direkt oder indirekt über Schnittstellen übermitteln, werden von
            <?php echo $operator['companyShortName'] ?> automatisch in ihren Server–Logfiles erhoben und gespeichert. Dies umfasst beispielsweise
            Browsertyp/ -version, verwendetes Betriebssystem, Referrer URL (die zuvor besuchte Seite), Hostname
            des zugreifenden Rechners (IP Adresse), übertragene Datenmenge, Meldung über erfolgreichen Abruf
            und Uhrzeit der Serveranfrage. Zusätzliche personenbezogene Daten werden nur dann erfasst, wenn Sie
            diese Angaben im Rahmen einer Anfrage sowie im Rahmen der Nutzer-Registrierung und der Profilerstellung
            freiwillig bei <?php echo $operator['companyShortName'] ?> machen. Die Registrierung bei <?php echo $operator['companyShortName'] ?> ist ausschließlich Personen über
            16 Jahren vorbehalten. Eltern oder Aufsichtsberechtigte sind für den Schutz der Privatsphäre ihrer
            Kinder verantwortlich.
        </li>
        <li class="wow fadeInLeft">
            <h4>Nutzung und Weitergabe personenbezogener Daten</h4>
            Personenbezogene Daten, die Sie als registrierter Nutzer <?php echo $operator['companyShortName'] ?> zur Verfügung gestellt haben,
            werden elektronisch gespeichert. Sie haben als Nutzer jederzeit die Möglichkeit, Daten entweder
            direkt aus Ihrem Profil zu löschen oder aber festzulegen, welche Nutzer Ihre Daten nicht einsehen
            dürfen. Ihre personenbezogenen Daten werden nur an Dritte weitergegeben, wenn dies dem
            Leistungszweck dient. Sie haben außerdem das Recht, die Löschung Ihrer Daten auf schriftlichem
            Wege zu veranlassen. Den Detailgrad dieser Daten bestimmen Sie selbst. Der aktuelle
            Detaillierungsgrad ist jeweils in Ihrem Profil ersehen. Die personenbezogenen Daten werden gemäß
            den Leistungen von <?php echo $operator['companyShortName'] ?> und für die technische Administration verwendet. <?php echo $this->company_name ?> gibt
            keine Daten zu Werbe- oder Marketingzwecken weiter, die Rückschlüsse auf Personen erlauben. Ihre
            anonymisierten Nutzerdaten verwenden wir für Zwecke der Beratung, der Werbung, der Marktforschung
            und zur Verbesserung und bedarfsgerechten Gestaltung des Dienstes. Ein Widerruf ist schriftlich
            möglich.
        </li>
        <li class="wow fadeInLeft">
            <h4>Verwendung von Cookies</h4>
            <?php echo $operator['companyShortName'] ?> verwendet an mehreren Stellen der Webseite so genannte Cookies. Das sind kleine
            Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr Browser speichert. Sie dienen dazu,
            unsere Webseite nutzerfreundlicher, effektiver und sicherer zu machen. Die meisten der von uns
            verwendeten Cookies sind so genannte „Session-Cookies“. Cookies richten auf Ihrem Rechner keinen
            Schaden an und enthalten keine Viren. Möchten Sie eine Speicherung dennoch verhindern, so können
            Sie dies durch entsprechende Einstellungen in Ihrem Browser verhindern.
        </li>
        <li class="wow fadeInLeft">
            <h4>Analyse-Software</h4>
            <?php echo $this->company_name ?> nutzt zur Erhebung von generellen Nutzerstatistiken auf Matomo zurück.
            <?php echo $this->piwik_opt_out ?>
        </li>
        <li class="wow fadeInLeft">
            <h4>Datensicherheit</h4>
            Durch technische und organisatorische Maßnahmen werden unsere Webseiten gegen Verlust, Zerstörung,
            Zugriff, Veränderung oder Verbreitung Ihrer Daten durch unbefugte Personen geschützt. Der Zugang zu
            Ihrem Profil erfolgt nur über die Eingabe ihres Logins in Verbindung mit Ihrem Passwort bzw. über
            definierte Schnittstellen u.a. zu Facebook. Die Zugriffsrechte können Sie im jeweiligen Account
            beschränken und/oder löschen. <?php echo $operator['companyShortName'] ?> verschickt keine Emails mit der Aufforderung Ihr Passwort
            einzugeben. Sie sollten Ihre Zugangsdaten stets vertraulich behandeln und sich nach Abschluss Ihrer
            Session abmelden, insbesondere wenn sie an öffentlichen Computern arbeiten oder sich Ihren Rechner
            mit anderen Nutzern teilen. Trotz aller Vorkehrungen ist aus technischen Gründen eine vollständige
            Sicherheit nicht realisierbar. Wir bitten Sie, uns bei Missbrauch oder bei Anzeichen von Missbrauch
            sofort zu informieren. Wir werden umgehend entsprechende Maßnahmen ergreifen.
        </li>
        <li class="wow fadeInLeft">
            <h4>Auskunftsrecht</h4>
            Wir geben Ihnen jederzeit darüber Auskunft welche Daten die bezüglich Ihrer Person, deren Herkunft
            und Empfänger sowie zu welchem Zweck gespeichert sind. Dazu reicht eine schriftliche Anfrage an die
            im <a href="<?php echo $this->basePath("/de/content/about#impressum")?>">Impressum</a> angegebene Adresse. Aus
            Sicherheitsgründen bitten wir Sie eine Kopie des Personalausweises beizulegen.
        </li>
        <li class="wow fadeInLeft">
            <h4>Änderungen der Datenschutzerklärung</h4>
            Das Datenschutzrecht ändert sich regelmäßig. Auch neue Serviceleistungen kommen hinzu. Deshalb
            behält sich die <?php echo $operator['companyShortName'] ?> das Recht vor, diese Datenschutzerklärungen jederzeit zu ändern. Sie
            werden als Nutzer von <?php echo $operator['companyShortName'] ?> über diese Änderungen per Email informiert.
        </li>
        <li class="wow fadeInLeft">
            <h4>Sicherheitshinweis</h4>
            Wir ergreifen alle technischen und organisatorischen Möglichkeiten, um Ihre personenbezogenen
            Daten so zu speichern, dass sie für Dritte nicht zugänglich sind. Vor allem bei E Mail Verkehr
            kann die vollständige Datensicherheit jedoch generell nicht sichergestellt werden. Wir empfehlen
            Ihnen deshalb, bei vertraulichen Informationen den Postweg zu nutzen.
        </li>
        <li class="wow fadeInLeft">
            <h4>Weitere Informationen</h4>
            Wenn Sie weitere Fragen haben, die diese Datenschutzerklärung beantwortet, dann wenden Sie sich
            bitte jederzeit an die Geschäftsführung von <?php echo $operator['companyShortName'] ?>, um weitere Informationen zu erhalten.
            Die Anschrift finden Sie unter <a href="<?php echo $this->basePath("/de/content/about#impressum")?>">Impressum</a>.
        </li>
    </ol>
</section>

