<?php
/**
 * YAWIK - Karriere24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html
$lang = $this->params('lang');
$notifications = $this->partial('core/notifications');


$this->headLink()->prependStylesheet($this->basePath('dist/css/core.min.css'));
$this->configHeadScript()->prependFile($this->basepath('dist/js/core.js'));
$this->configHeadScript()->appendFile($this->basePath('modules/Karriere24/dist/karriere24.js'));

$langScript = 'dist/locales/' . $lang . '.js';
$this->configHeadScript()->appendFile($this->basePath($langScript));

$this->configHeadScript()->appendScript('var lang="' . $lang . '";'
                                        . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->appendStylesheet($this->basePath('modules/Karriere24/animate.min.css'));
$this->headLink()->appendStylesheet($this->basePath('modules/Karriere24/dist/Karriere24.css'));

?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang')?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Karriere24')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="keywords" content="Bewerbermanagement System, Bewerberverwaltung"/>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>
<a class="sr-only" href="#content">Skip to main content</a>
<header id="top" role="banner" class="container-fluid">
    <div class="navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target=".cam-navbar-collapse" data-toggle="collapse"
                    type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand hidden-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>"><?=$this->translate('Karriere24', \Karriere24\Module::TEXT_DOMAIN)?></a>
            <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">Y</a>
        </div>
        <nav id="main-navigation" class="navbar-collapse collapse" role="navigation">
            <?php
            echo $this->navigation('Core/Navigation')
                ->setAcl($this->services('acl'))
                ->setRole($this->auth('role'))
                ->menu()
                ->setMaxDepth(1) // only show the top level entries
                ->renderPartial(null, 'main-navigation')
            ?>
            <?php echo $this->loginInfo() ?>
        </nav>
        <!-- /main-navigation -->
    </div>
</header>
<main id="content" class="coll-md-12">
     <div class="container-fluid">
     <?php echo $notifications?>
     <?php echo $this->content; ?>
     </div>
</main>
<!-- /container -->
<footer id="footer">
    <div class="container-fluid">
                <span class="pull-left"><small>&copy; <?php echo date("Y")?> Karriere24. <?php echo $this->translate('All rights reserved.') ?>
                         </small></span>
                <span class="pull-right"><small>
                      <a href="<?php echo $this->basePath("/content/about#impressum")?>">Impressum</a> | Powered by <a href="http://yawik.org">YAWIK</a>
                    </small> </span>
    </div>
</footer>
<?php echo $this->partial("piwik")?>
<script>
  new cookieNoticeJS({

    // Localizations of the notice message
    'messageLocales': {
      'it': 'Custom localized message'
    },

    // Localizations of the dismiss button text
    'buttonLocales': {
      'it': 'Chiudi'
    },

    // Position for the cookie-notifier (default=bottom)
    'cookieNoticePosition': 'bottom',

    // Shows the "learn more button (default=false)
    'learnMoreLinkEnabled': true,

    // The href of the learn more link must be applied if (learnMoreLinkEnabled=true)
    'learnMoreLinkHref': '/de/content/about',

    // Text for optional learn more button
    'learnMoreLinkText':{
      'en':'learn more'
    },

    // The message will be shown again in X days
    'expiresIn': 30,

    // Dismiss button background color
    'buttonBgColor': '#d35400',

    // Dismiss button text color
    'buttonTextColor': '#fff',

    // Notice background color
    'noticeBgColor': '#000',

    // Notice text color
    'noticeTextColor': '#fff',

    // the learnMoreLink color (default='#009fdd')
    'linkColor': '#f00',

    // The target of the learn more link (default='', or '_blank')
    'linkTarget': '',

    // Print debug output to the console (default=false)
    'debug': false
  });
</script>
</body>
</html>
